--EXEC sp_helpindex '[dbo].[PERSON]'

USE [NEWBASE]
GO

DROP INDEX IF EXISTS [dbo].[INDEX_PUBLICATION].[IX_INDEX_PUBLICATION];
CREATE INDEX IX_INDEX_PUBLICATION
ON [dbo].[INDEX_PUBLICATION](GENRE_ID, AUTHOR, PUBLICATION_TITLE);

GO
DROP INDEX IF EXISTS [dbo].[MOVIE].[IX_INDEX_MOVIE];
CREATE INDEX IX_INDEX_MOVIE
ON [dbo].[MOVIE](GENRE_ID, [YEAR], MOVIE_TITLE);

GO
DROP INDEX IF EXISTS [dbo].[PERSON].[IX_NAME_COUNTRY];
CREATE INDEX IX_NAME_COUNTRY
ON [dbo].[PERSON](F_NAME, L_NAME, COUNTRY_ID);

DROP INDEX IF EXISTS [dbo].[STUDENTS BY MAJOR AND YEAR].[IX_STUDENT_MAJOR_YEAR];
CREATE INDEX IX_STUDENT_MAJOR_YEAR
ON [dbo].[STUDENTS BY MAJOR AND YEAR](MAJOR,[YEAR]);