USE NEWBASE
GO

DROP TRIGGER IF EXISTS GRADE_INSERT
GO
CREATE TRIGGER GRADE_INSERT 
ON GRADE
AFTER INSERT 
AS 
  BEGIN
    PRINT 'INSERT INTO THIS TABLE IS NOT ALLOWED.'
	ROLLBACK TRANSACTION
  END
GO

INSERT INTO GRADE(GRADE_NAME) VALUES ('14')

GO

--CREATED HISTORY_LOG AND TRIGGER FOR COUNTRY_OF_ORIGIN
DROP TABLE IF EXISTS HISTORY_LOG;
CREATE TABLE HISTORY_LOG(
  ID INT IDENTITY PRIMARY KEY,
  ORIGINAL_ID INT,
  "ACTION" VARCHAR(70),
  "CREATED AT" DATETIME NOT NULL DEFAULT GETDATE()
)

DROP TRIGGER IF EXISTS COUNTRY_OF_ORIGIN_INSERT;
GO
CREATE TRIGGER COUNTRY_OF_ORIGIN_INSERT
ON COUNTRY_OF_ORIGIN
AFTER INSERT
AS
BEGIN
INSERT INTO HISTORY_LOG("ACTION") 
SELECT [ID_COUNTRY],'ADDED NEW COUNTRY INTO TABLE COUNTRY_OF_ORIGIN:   '+ COUNTRY_NAME
FROM INSERTED
END

INSERT INTO COUNTRY_OF_ORIGIN VALUES('Nicaragua2')

SELECT * FROM [dbo].[COUNTRY_OF_ORIGIN]
ORDER BY ID_COUNTRY

SELECT * FROM HISTORY_LOG
--END OF COUNTRY_OF_ORIGIN TRIGGER

--ADD NEW GENRE_PUBLICATION AND CREATE TRIGGER FOR NOTIFICATION AND ONOTHER FOR HISTORY_LOG
INSERT INTO GENRE_PUBLICATION(GENRE_NAME) VALUES('SCI-FI1')
--SELECT * FROM GENRE_PUBLICATION
--DELETE FROM GENRE_PUBLICATION WHERE ID_GENRE>2

--ALTER TABLE [dbo].[GENRE_PUBLICATION] ADD CONSTRAINT UC_GENRE_NAME UNIQUE(GENRE_NAME) 
--ALTER TABLE [dbo].[GENRE_PUBLICATION] DROP CONSTRAINT UC_GENRE_NAME 

DROP TRIGGER IF EXISTS GENRE_PUBLICATION_ADD;
GO
CREATE TRIGGER GENRE_PUBLICATION_ADD
ON GENRE_PUBLICATION
AFTER INSERT 
AS
BEGIN
PRINT 
'A NEW GENRE IS INSERTED INTO THE GENRE_PUBLICATION TABLE'
END
GO

DROP TRIGGER IF EXISTS GENRE_PUBLICATION_INSERT;
GO
CREATE TRIGGER GENRE_PUBLICATION_INSERT
ON
GENRE_PUBLICATION
AFTER INSERT
AS
BEGIN
INSERT INTO HISTORY_LOG(ORIGINAL_ID, "ACTION")
SELECT ID_GENRE,'ADDED A NEW GENRE: ' + GENRE_NAME
FROM INSERTED
END

SELECT * FROM HISTORY_LOG
SELECT * FROM [dbo].[GENRE_PUBLICATION]








SELECT * FROM HISTORY_LOG

INSERT INTO [dbo].[COUNTRY_OF_ORIGIN](COUNTRY_NAME)
VALUES ('UAE');

DELETE FROM [dbo].[COUNTRY_OF_ORIGIN]
WHERE ID_COUNTRY>42

UPDATE [dbo].[COUNTRY_OF_ORIGIN]
SET COUNTRY_NAME = 'Iceland'
WHERE ID_COUNTRY=65

SELECT * FROM [dbo].[COUNTRY_OF_ORIGIN]
ORDER BY ID_COUNTRY




)



