--EXEC sp_tables @table_type = "'VIEW'", @TABLE_OWNER=DBO;

--THE VIEWS
USE NEWBASE
GO

DROP VIEW IF EXISTS [dbo].[STUDENTS BY ORIGIN];
GO
CREATE VIEW [STUDENTS BY ORIGIN] AS
SELECT COUNTRY_NAME [COUNTRY], COUNT(ID_PERSON) AS [NUMBER OF STUDENTS]
FROM [dbo].[COUNTRY_OF_ORIGIN]
JOIN [dbo].[PERSON]
ON [ID_COUNTRY]=[COUNTRY_ID]
GROUP BY COUNTRY_NAME;

GO
DROP VIEW IF EXISTS [dbo].[NUMBER OF STUDENTS];
GO
CREATE VIEW [NUMBER OF STUDENTS] AS
SELECT MAJOR_NAME, COUNT(ID_PERSON) [NUMBER OF STUDENTS]
FROM [dbo].[MAJOR]
JOIN [dbo].[STUDENT]
ON [ID_MAJOR]=[MAJOR_ID]
JOIN [dbo].[PERSON]
ON [ID_PERSON]=[PERSON_ID]
GROUP BY [MAJOR_NAME];

GO
DROP VIEW IF EXISTS [dbo].[MANNING TABLE];
GO
CREATE VIEW [MANNING TABLE] AS
SELECT ID_PERSON, F_NAME [FIRST NAME], L_NAME [LAST NAME], POSITION, MAJOR_NAME AS MAJOR, ENTRY_DATE 
FROM [dbo].[STAFF]
JOIN [dbo].[PERSON] 
ON ID_PERSON=PERSON_ID
JOIN [dbo].[MAJOR]
ON [ID_MAJOR]=STAFF.[MAJOR_ID];

GO
DROP VIEW IF EXISTS [dbo].[BOOK TOP 20 LIST]
GO
CREATE VIEW [BOOK TOP 20 LIST] AS
SELECT TOP 20 [PUBLICATION_TITLE], [AUTHOR], [GENRE_NAME] AS GENRE, COUNT(INDEX_ID) [NUMBER OF READERS]
FROM [dbo].[ITEM_TAKEN]
JOIN [dbo].[INDEX_PUBLICATION]
ON [ID_INDEX]=[INDEX_ID]
JOIN [dbo].[GENRE_PUBLICATION]
ON [GENRE_ID]=[ID_GENRE]
GROUP BY INDEX_ID, [PUBLICATION_TITLE], [AUTHOR], GENRE_ID, [GENRE_NAME];

GO
DROP VIEW IF EXISTS [dbo].[TOP 10 MOVIES];
GO
CREATE VIEW [TOP 10 MOVIES] AS
SELECT TOP 10 [MOVIE_TITLE], COUNT(MOVIE_ID) [NUMBER OF SESSIONS]
FROM [dbo].[CINEMA]
JOIN [dbo].[MOVIE]
ON [MOVIE_ID]=[ID_MOVIE]
GROUP BY [MOVIE_TITLE];

GO
DROP VIEW IF EXISTS [dbo].[CANTEEN ORDERS];
GO
CREATE VIEW [CANTEEN ORDERS] AS 
SELECT F_NAME, L_NAME, PERSON_ID, QUANTITY, MEAL_NAME, MEAL_PRICE, (MEAL_PRICE*QUANTITY) AS MONEY_PAID, MEAL_DATE
FROM [dbo].[MEAL_TAKEN]
JOIN [dbo].[MEAL]
ON MEAL_ID=ID_MEAL
JOIN PERSON P
ON ID_PERSON=PERSON_ID
WHERE QUANTITY > 1;

GO
DROP VIEW IF EXISTS [dbo].[LAUNDRY SERVICE];
GO
CREATE VIEW [LAUNDRY SERVICE] AS 
SELECT PERSON_ID, F_NAME [NAME], L_NAME [LAST NAME], COUNT(PERSON_ID) [QUANTITY], PRICE [PRICE], SUM(PRICE) [SUM PAID]
FROM [dbo].[LAUNDRY]
JOIN [dbo].[PERSON]
ON [PERSON_ID]=[ID_PERSON]
JOIN [dbo].[LAUNDRY_PRICE]
ON [L_PRICE_ID]=[ID_LAUNDRY_PRICE]
GROUP BY PERSON_ID, F_NAME,  L_NAME, PRICE;

GO
DROP VIEW IF EXISTS [dbo].[CONTACT INFO];
GO
CREATE VIEW [CONTACT INFO] AS
SELECT [ID_PERSON]
      ,[F_NAME]
      ,[L_NAME]
	  ,[PHONE_NUMBER]
      ,[EMAIL]
      ,[STATUS]
  FROM [dbo].[PERSON];

  GO
DROP VIEW IF EXISTS [dbo].[STUDENTS BY MAJOR AND YEAR];
GO
CREATE VIEW [STUDENTS BY MAJOR AND YEAR] AS 
SELECT F_NAME [FIRST NAME], L_NAME [LAST NAME], MAJOR_NAME [MAJOR], 2021-YE AR(ENTRY_DATE) [YEAR OF STUDY]
FROM STUDENT
JOIN PERSON
ON ID_PERSON=PERSON_ID
JOIN MAJOR
ON ID_MAJOR=MAJOR_ID;


GO
SELECT * FROM [STUDENTS BY ORIGIN]
ORDER BY [NUMBER OF STUDENTS] DESC


SELECT * FROM [dbo].[NUMBER OF STUDENTS]
ORDER BY [NUMBER OF STUDENTS] DESC


SELECT * FROM [MANNING TABLE]
ORDER BY MAJOR, ENTRY_DATE 


SELECT * FROM [BOOK TOP 20 LIST]
ORDER BY [NUMBER OF READERS] DESC

SELECT * FROM [CANTEEN ORDERS]


SELECT * FROM [dbo].[TOP 10 MOVIES]
ORDER BY [NUMBER OF SESSIONS] DESC


SELECT * FROM [dbo].[LAUNDRY SERVICE]
ORDER BY QUANTITY DESC


SELECT * FROM [dbo].[CONTACT INFO]


SELECT * FROM [dbo].[STUDENTS BY MAJOR AND YEAR]
ORDER BY [YEAR OF STUDY] DESC, MAJOR